In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
!curl -L -o car_fuel_efficiency_2026.csv https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  620k  100  620k    0     0  1466k      0 --:--:-- --:--:-- --:--:-- 1469k

In [4]:
import pandas as pd

df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [6]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df.horsepower.median()

np.float64(254.0)

In [9]:
# Find the median value of the horsepower column in the dataset.
# Next, calculate the most frequent value of the same horsepower column.
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.

In [20]:
most_Frequent

0    252.0
Name: horsepower, dtype: float64

In [25]:
most_frequent = df["horsepower"].mode().iloc[0]
df["horsepower"] = df["horsepower"].fillna(most_frequent)

In [26]:
df.horsepower.isnull().sum()

np.int64(0)

In [27]:
df.horsepower.median()

np.float64(252.0)

In [28]:
# Q7. Sum of weights
# Select all the cars from Asia
# Select only columns vehicle_weight and model_year
# Select the first 7 values
# Get the underlying NumPy array. Let's call it X.
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# Invert XTX.
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the sum of all the elements of the result?
# Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [12]:
test = df[df['origin']=='Asia']

In [14]:
X=test[['vehicle_weight','model_year']].head(7).values

In [15]:
XTX = X.T @X

In [16]:
#inverse of XTX

XTX_inv = np.linalg.inv(XTX)

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [18]:
w = XTX_inv @ X.T @ y

In [19]:
answer = w.sum()

In [20]:
print(w)

[0.13644777 0.2327492 ]

In [21]:
print(answer)

0.36919696904925486